site_name: AI Landscape
site_description: Documentation for AI architectures, tools, and foundations.
site_url: https://jaojbls.github.io/ai-landscape/

theme:
  name: material
  palette:
    - scheme: default
      primary: black
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
  features:
    - navigation.sections
    - search.suggest
    - search.highlight
    - toc.integrate

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - admonition
  - pymdownx.details

plugins:
  - search
  - macros

# No nav block needed. MkDocs will use index.md as the single page.
